version: '3'

services:
  task-service:
    container_name: task-service
    image: 'nota-tabula/task-service:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    networks:
      - spring-cloud-network
  security-service:
    container_name: security-service
    image: 'nota-tabula/task-service:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8081:8081
    networks:
        - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge