spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://nota-tabula.ctezjyhwnobs.eu-central-1.rds.amazonaws.com:5432/tasks
    username: postgres
    password: password
  jpa:
    show-sql: true

server:
  port: 8080