spring:
  application:
    name: Task-Service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://nota-tabula.ctezjyhwnobs.eu-central-1.rds.amazonaws.com:5432/tasks
    username: postgres
    password: password
    tomcat:
      min-idle: 8
      initial-size: 50
      max-idle: 150
      max-active: 300
      max-wait: 20000
  jpa:
    show-sql: true

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true